export const INIT_LOGIN = "INIT_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const SET_OAUTH_STATE = "SET_OAUTH_STATE";
export const PROPOGATE_CODE = "PROPOGATE_CODE";

export const INIT_QUERY = "INIT_QUERY";
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_FAILURE = "FETCH_STUDENTS_FAILURE";
export const FETCH_ALL_REPOS_SUCCESS = "FETCH_ALL_REPOS_SUCCESS";
export const FETCH_ALL_REPOS_FAILURE = "FETCH_ALL_REPOS_FAILURE";
export const FETCH_REPO_SUCCESS = "FETCH_REPO_SUCCESS";
export const FETCH_REPO_FAILURE = "FETCH_REPO_FAILURE";
export const FETCH_COMMITS_SUCCESS = "FETCH_COMMITS_SUCCESS";
export const FETCH_COMMITS_FAILURE = "FETCH_COMMITS_FAILURE";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";
